### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 39612** [CanMik/protocolsmanager#1]
GLPI version :GLPI 10.0.1
[https://github.com/CanMik/protocolsmanager/releases/tag/v1.5.2](url)
When trying to install it gives the following error:
`SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD author_state int(2) AFTER author_name' at line 4 in query "ALTER TABLE glpi_plugin_protocolsmanager_config ADD author_name varchar(255) AFTER email_template ADD author_state int(2) AFTER author_name"
- Erro durante a consulta da base de dados: ALTER TABLE glpi_plugin_protocolsmanager_config ADD author_name varchar(255) AFTER email_template ADD author_state int(2) AFTER author_name - Erro é You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD author_state int(2) AFTER author_name' at line 4
R
Reports
GPLv3+
Nelly Mahu-Lasson, Remi Collet
2.0.0`

**Comment by CanMik** [comment]
Hello have you tried to uninstall reinstall the plugin ?
