### ISSUE TITLE
Comment / Note misleading

### ISSUE THREAD

**Issue by petertuharsky** [CanMik/protocolsmanager#16]
Hi,

when I create the Protocol from User's tab, there is a field with grey "Note" background, and the Comments field. Both are editable.
After filling in, the text entered in "Note" goes to "Comment" of the created document, and the "Comments" field goes into the protocol (PDF) as Comments column.

This is quite misleading.

![obrázok](https://github.com/CanMik/protocolsmanager/assets/119676775/1489d532-d955-47a0-bd83-d8451e5f7a63)
![obrázok](https://github.com/CanMik/protocolsmanager/assets/119676775/ad716334-c733-4c25-88b4-35b6279a7e19)
![obrázok](https://github.com/CanMik/protocolsmanager/assets/119676775/735f5fcd-0326-4f36-85e1-e2506b7cbfbc)

**Comment by CanMik** [comment]
Changed names on the lastest version of master
