### ISSUE TITLE
Can't create new templates

### ISSUE THREAD

**Issue by Degaion** [CanMik/protocolsmanager#3]
Hi, thank you so much for your usefull plugin.

I have an issue, when i'm trying to add a templeate and then press the button "submit", the template doesn't adds to a list of templates.

Anyone with this issue too?

**Comment by CanMik** [comment]
Hello Degaion sorry for the delay,
Can you tell me the version of php and glpi you are currently using.
I've tried to replicate the issue with the stable version I've been using which is : php 8.0.15 and glpi 10.0.0.
I may think you are using a version of PHP below 8.0 maybe 7.4 ?

**Comment by Degaion** [comment]
Hello, thank you for your answer.

I just find that was my mistake because before to create a new protocol template i have need to create an aditional emal templeate for that new protocol template.

I am using GLPI 10 and PHP 8.0.

Now i have another issue with the plugin (sorry but i need help): When i adding custom fields, the headers does not correspondig whit his fields, im attaching a video for better refference.

https://user-images.githubusercontent.com/116742931/205380247-b2bacdc9-6b1a-4fc3-92cc-818275a53b1f.mp4
