### ISSUE TITLE
SIM does not show

### ISSUE THREAD

**Issue by VLuisVLT** [CanMik/protocolsmanager#4]
When a SIM is added to an user, the protocols tab keep in a loop and never loads
![MolsHY4p2R](https://user-images.githubusercontent.com/109097647/214172136-4dfcaef8-3d30-4a32-8294-3617498b8f36.png)

**Comment by CanMik** [comment]
Hello Luis I published a new release I hope it fixes your issues : https://github.com/CanMik/protocolsmanager/releases/tag/v1.5
If it doesn't fix, can you give me more information about your version of PHP, glpi and maybe activate debug mode.

**Comment by VLuisVLT** [comment]
Hi CanMik, the realese fix the issue. Thanks a lot!
